name: Release Build

# Only on release tags.
on:
#  push:
#    tags:
#      - v[0-9]+.[0-9]+.[0-9]+

  # Allows you to run this workflow manually from the Actions tab (for testing)
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:

    name: "Package Tagged Extension"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout local repository"
        uses: actions/checkout@v3

      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install vscode package tool
        run: npm install -g vsce

      - name: npm install
        run: npm install

      - name: npm lint
        run: npm run lint

      # TODO: binaries from formatter_server repo.

      - name: npm build webpack version
        run: npm run webpack

      - name: set version
        run: |
          CURRENT_VERSION=$(node -p -e "require('./package.json').version")
          NEW_VERSION=$CURRENT_VERSION.$(date +%F)
          npm version $NEW_VERSION --no-git-tag-version

      - name: vsce package
        run: vsce package

      - name: Store vsix
        uses: actions/upload-artifact@v3
        with:
          name: release-build-vsix
          path: "*.vsix"
